<!DOCTYPE html>
<html lang="fr">
<head>
	<link rel="shortcut icon" type="image/x-icon" href="img/logo3.png" />
	
	<link href="bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="stylelearn.css" rel="stylesheet">
    <link href="responsive.css" rel="stylesheet">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />	
</head>
<body>
	<div id="pageCaptcha">

<?php

function motListe()
{
	$liste = array('internet', 'captcha', 'robot', 'anglais', 'test',
'ABACOST', 'ABACULE', 'ABAISSA', 'ABAISSE', 'ABAJOUE', 'ABALONE', 'ABANDON' , 'ABAQUES',	
'CALMARS', 'CALMEES', 'CALMENT', 'CALMERA', 'CALMIEZ', 'CALMIRA', 'CALMONS' , 'CALOMEL',
'CALORIE', 'CALOTIN', 'CALOTTA', 'CALOTTE', 'CALOYER', 'CALQUAI', 'CALQUAS' , 'CALQUAT',
'CALQUEE', 'CALQUER', 'CALQUES', 'CALQUEZ', 'CALTAIS', 'CALTAIT', 'CALTANT' , 'CALTEES',
'CALTENT', 'CALTERA', 'CALTIEZ', 'CALTONS', 'CALUGEA', 'CALUGER', 'CALUGES' , 'CALUGEZ',
'CALUMET', 'CALURES', 'CALYPSO', 'CALZONE', 'CAMAIEU', 'CAMAILS', 'CAMAMES' , 'CAMARDE',
'CAMARDS', 'CAMASSE', 'CAMATES', 'CAMBAIS', 'CAMBAIT', 'CAMBALA', 'CAMBALE' , 'CAMBANT',
'CAMBEES', 'CAMBENT', 'CAMBERA', 'CAMBIAL', 'CAMBIEZ', 'CAMBIUM', 'CAMBONS' , 'CAMBRAI',
'CAMBRAS', 'CAMBRAT', 'CAMBREE', 'CAMBRER', 'CAMBRES', 'CAMBREZ', 'CAMBUSE' , 'CAMELIA',
'CAMELLE', 'CAMELOT', 'CAMERAI', 'CAMERAL', 'CAMERAS', 'CAMEREZ', 'CAMIONS' , 'CAMORRA',
'CAMPAIS', 'CAMPAIT', 'CAMPANE', 'CAMPANT', 'CAMPEES', 'CAMPENT', 'CAMPERA' , 'CAMPEUR',
'CAMPHRA', 'CAMPHRE', 'CAMPIEZ', 'CAMPING', 'CAMPONS', 'CAMUSES', 'CANADAS' , 'CANAMES',
'CANAPES', 'CANAQUE', 'CANARAS', 'CANARDA', 'CANARDE', 'CANARDS', 'CANARIS' , 'CANASSE',
'CANASTA', 'CANATES', 'CANCALE', 'CANCANA', 'CANCANE', 'CANCANS', 'CANCELS' , 'CANCERS',
'CANCHES', 'CANCRES', 'CANDACE', 'CANDELA', 'CANDEUR', 'CANDIDA', 'CANDIDE' , 'CANDIES',
'CANDIRA', 'CANEPIN', 'CANERAI', 'CANERAS', 'CANEREZ', 'CANETON', 'CANETTE' , 'CANEVAS','COACHAT', 'COACHEE', 'COACHER', 'COACHES', 'COACHEZ', 'COACTIF', 'COAGULA' , 'COAGULE',
'COALISA', 'COALISE', 'COALTAR', 'COASSAI', 'COASSAS', 'COASSAT', 'COASSER' , 'COASSES',
'COASSEZ', 'COAXIAL', 'COBAEAS', 'COBALTS', 'COBAYES', 'COBIERS', 'COCAGNE' , 'COCAIER',
'COCAINE', 'COCARDE', 'COCASSE', 'COCCIDE', 'COCHAIS', 'COCHAIT', 'COCHANT' , 'COCHEES',
'COCHENT', 'COCHERA', 'COCHERE', 'COCHERS', 'COCHETS', 'COCHIEZ', 'COCHLEE' , 'COCHONS',
'COCKERS', 'COCKNEY', 'COCKPIT', 'COCOLAI', 'COCOLAS', 'COCOLAT', 'COCOLEE' , 'COCOLER',
'COCOLES', 'COCOLEZ', 'COCONNA', 'COCONNE', 'COCOONA', 'COCOONE', 'COCOONS' , 'COCOTAI',
'COCOTAS', 'COCOTAT', 'COCOTER', 'COCOTES', 'COCOTEZ', 'COCOTTA', 'COCOTTE' , 'COCTION',
'COCUAGE', 'COCUFIA', 'COCUFIE', 'CODAGES', 'CODAMES', 'CODANTE', 'CODANTS' , 'CODASSE',
'CODATES', 'CODEINE', 'CODERAI', 'CODERAS', 'CODEREZ', 'CODEURS', 'CODEUSE' , 'CODIFIA',
'CODIFIE', 'CODIONS', 'COEDITA', 'COEDITE', 'COELOME', 'COENURE', 'COFFINS' , 'COFFRAI',
'COFFRAS', 'COFFRAT', 'COFFREE', 'COFFRER', 'COFFRES', 'COFFRET', 'COFFREZ' , 'COGERAI',
'COGERAS', 'COGERAT', 'COGEREE', 'COGERER', 'COGERES', 'COGEREZ', 'COGITAI' , 'COGITAS',
'COGITAT', 'COGITEE', 'COGITER', 'COGITES', 'COGITEZ', 'COGITOS', 'COGNACS' , 'COGNAIS',
'COGNAIT', 'COGNANT', 'COGNATS', 'COGNEES', 'COGNENT', 'COGNERA', 'COGNEUR' , 'COGNIEZ',
'COGNONS', 'COHESIF', 'COHOBAI', 'COHOBAS', 'COHOBAT', 'COHOBEE', 'COHOBER' , 'COHOBES',
'COHOBEZ', 'COHORTE', 'COIFFAI', 'COIFFAS', 'COIFFAT', 'COIFFEE', 'COIFFER' , 'COIFFES',
'COIFFEZ', 'COINCAI', 'COINCAS', 'COINCAT', 'COINCEE', 'COINCER', 'COINCES' , 'COINCEZ',
'COINCHA', 'COINCHE', 'COITAIS', 'COITAIT', 'COITANT', 'COITENT', 'COITERA' , 'COITIEZ',
'COITONS', 'COITRON', 'COITTES', 'COKAGES', 'COKEFIA', 'COKEFIE', 'COKERIE' , 'COKEURS',
'COKINGS', 'COLBACK', 'COLERES', 'COLIBRI', 'COLINOT', 'COLIQUE', 'COLISAI' , 'COLISAS',
'COLISAT', 'COLISEE', 'COLISER', 'COLISES', 'COLISEZ', 'COLITES', 'COLLABO' , 'COLLAGE',
'COLLAIS', 'COLLAIT', 'COLLANT', 'COLLEES', 'COLLEGE', 'COLLENT', 'COLLERA' , 'COLLETA',
'COLLETE', 'COLLETS', 'COLLEUR', 'COLLEYS', 'COLLIER', 'COLLIEZ', 'COLLIGE' , 'COLLINE',
'COLLONS', 'COLLURE', 'COLLYRE', 'COLMATA', 'COLMATE', 'COLOBES', 'COLOMBE' , 'COLOMBO',
'COLONAT', 'COLONEL', 'COLONES', 'COLONIE', 'COLONNE', 'COLORAI', 'COLORAS' , 'COLORAT',
'COLOREE', 'COLORER', 'COLORES', 'COLOREZ', 'COLORIA', 'COLORIE', 'COLORIS' , 'COLOSSE',
'COLTANS', 'COLTINA', 'COLTINE', 'COLTINS', 'COLURES', 'COLVERT', 'COMATAI' , 'COMATAS',
'COMATAT', 'COMATER', 'COMATES', 'COMATEZ', 'COMBATS', 'COMBAVA', 'COMBIEN' , 'COMBINA',
'COMBINE', 'COMBLAI', 'COMBLAS', 'COMBLAT', 'COMBLEE', 'COMBLER', 'COMBLES' , 'COMBLEZ',
'COMEDIE', 'COMEDON', 'COMETES', 'COMICES', 'COMIQUE', 'COMITAT', 'COMITES' , 'COMMAND',
'COMMENT', 'COMMERA', 'COMMERE', 'COMMETS', 'COMMISE', 'COMMODE', 'COMMUAI' , 'COMMUAS',
'COMMUAT', 'COMMUEE', 'COMMUER', 'COMMUES', 'COMMUEZ', 'COMMUNE', 'COMMUNS' , 'COMMUTA',
'COMMUTE', 'COMPACT', 'COMPARA', 'COMPARE', 'COMPARU', 'COMPATI', 'COMPERE' , 'COMPETA',
'COMPETE', 'COMPETI', 'COMPILA', 'COMPILE', 'COMPILS', 'COMPLET', 'COMPLOT' , 'COMPLUS',
'FRIPONS', 'FRIQUEE', 'FRIQUES', 'FRIQUET', 'FRIRAIS', 'FRIRAIT', 'FRIRIEZ' , 'FRIRONS',
'FRIRONT', 'FRISAGE', 'FRISAIS', 'FRISAIT', 'FRISANT', 'FRISBEE', 'FRISEES' , 'FRISENT',
'FRISERA', 'FRISIEZ', 'FRISKOS', 'FRISONS', 'FRISSON', 'FRISURE', 'FRITAIS' , 'FRITAIT',
'FRITANT', 'FRITEES', 'FRITENT', 'FRITERA', 'FRITIEZ', 'FRITONS', 'FRITOTS' , 'FRITTAI',
'FRITTAS', 'FRITTAT', 'FRITTEE', 'FRITTER', 'FRITTES', 'FRITTEZ', 'FRITURE' , 'FRIVOLE',
'FROCARD', 'FROIDES', 'FROISSA', 'FROISSE', 'FROLAIS', 'FROLAIT', 'FROLANT' , 'FROLEES',
'FROLENT', 'FROLERA', 'FROLEUR', 'FROLICS', 'FROLIEZ', 'FROLONS', 'FROMAGE' , 'FROMEGI',
'FROMENT', 'FROMGIS', 'FROMTON', 'FRONCAI', 'FRONCAS', 'FRONCAT', 'FRONCEE' , 'FRONCER',
'FRONCES', 'FRONCEZ', 'FRONCIS', 'FRONDAI', 'FRONDAS', 'FRONDAT', 'FRONDEE' , 'FRONDER',
'FRONDES', 'FRONDEZ', 'FRONSAC', 'FRONTAL', 'FRONTON', 'FROTTAI', 'FROTTAS' , 'FROTTAT',
'FROTTEE', 'FROTTER', 'FROTTES', 'FROTTEZ', 'FROTTIS', 'FROUAIS', 'FROUAIT' , 'FROUANT',
'FROUENT', 'FROUERA', 'FROUIEZ', 'FROUONS', 'FROUSSE', 'FRUCTUS', 'FRUGALE' , 'FRUGAUX',
'FRUITEE', 'FRUITES', 'FRUSTES', 'FRUSTRA', 'FRUSTRE', 'FUCACEE', 'FUCALES' , 'FUCHSIA',
'FUEGIEN', 'FUGACES', 'FUGITIF', 'FUGUAIS', 'FUGUAIT', 'FUGUANT', 'FUGUEES' , 'FUGUENT',
'FUGUERA', 'FUGUEUR', 'FUGUIEZ', 'FUGUONS', 'FUHRERS', 'FUIRAIS', 'FUIRAIT' , 'FUIRENT',
'FUIRIEZ', 'FUIRONS', 'FUIRONT', 'FUISSES', 'FUITAIS', 'FUITAIT', 'FUITANT' , 'FUITENT',
'FUITERA', 'FUITIEZ', 'FUITONS', 'FULGORE', 'FULGURA', 'FULGURE', 'FULMARS' , 'FULMINA',
'FULMINE', 'FUMABLE', 'FUMAGES', 'FUMAMES', 'FUMANTE', 'FUMANTS', 'FUMASSE' , 'FUMATES',
'FUMIGEA', 'FUMIGEE', 'FUMIGER', 'FUMIGES', 'FUMIGEZ', 'FUMIONS' , 'FUMISTE',
'FUMOIRS', 'FUMURES', 'FUNEBRE', 'FUNESTE', 'FURANES', 'FURANNE', 'FURCULA' , 'FURETAI',
'FURETAS', 'FURETAT', 'FURETER', 'FURETES', 'FURETEZ', 'FUREURS', 'FURIEUX' , 'FURIOSO',
'FUROLES', 'FURTIFS', 'FURTIVE', 'FUSAINS', 'FUSAMES', 'FUSANTE', 'FUSANTS' , 'FUSASSE',
'FUSATES', 'FUSCINE', 'FUSEAUX', 'FUSELAI', 'FUSELAS', 'FUSELAT', 'FUSELEE' , 'FUSELER',
'FUSELES', 'FUSELEZ', 'FUSELLE', 'FUSERAI', 'FUSERAS', 'FUSEREZ', 'FUSETTE' , 'FUSIBLE',
'FUSILLA', 'FUSILLE', 'FUSILLI', 'FUSIONS', 'FUSSENT', 'FUSSIEZ', 'FUSTETS' , 'FUSTIGE',
'FUSTINE', 'FUTAIES', 'FUTAINE', 'FUTILES', 'FUTSALS', 'FUTURES', 'FUXEENS' , 'FUYANTE',
'FUYANTS', 'FUYARDE', 'FUYARDS', 'FUYIONS', 'GABARES', 'GABARIA', 'GABARIE' , 'GABARIT',
'GABARRE', 'GABBROS', 'GABEGIE', 'GABELLE', 'GABELOU', 'GABIERS', 'GABIONS' , 'GACHAGE',
'GACHAIS', 'GACHAIT', 'GACHANT', 'GACHEES', 'GACHENT', 'GACHERA', 'GACHEUR' , 'GACHIEZ',
'GACHONS', 'GADELLE', 'GADGETS', 'GADIDES', 'GADITAN', 'GADOUES', 'GAFFAIS' , 'GAFFAIT',
'GAFFANT', 'GAFFEES', 'GAFFENT', 'GAFFERA', 'GAFFEUR', 'GAFFIEZ', 'GAFFONS' , 'GAGAKUS',
'GAGEAIS', 'GAGEAIT', 'GAGEANT', 'GAGEONS', 'GAGERAI', 'GAGERAS', 'GAGEREZ' , 'GAGERIE',
'GAGEURE', 'GAGEURS', 'GAGEUSE', 'GAGIONS', 'GAGISTE', 'GAGMANS', 'GAGNAGE' , 'GAGNAIS',
'GAGNAIT', 'GAGNANT', 'GAGNEES', 'GAGNENT', 'GAGNERA', 'GAGNEUR', 'GAGNIEZ' , 'GAGNONS',
'GAIACOL', 'GAIETES', 'GAILLAC', 'GAILLET', 'GAIMENT', 'GAINAGE', 'GAINAIS' , 'GAINAIT',
'GAINANT', 'GAINEES', 'GAINENT', 'GAINERA', 'GAINIER', 'GAINIEZ', 'GAINONS' , 'GALAGOS',
'GALANGA', 'GALANTE', 'GALANTS', 'GALATES', 'GALAXIE', 'GALBAIS', 'GALBAIT' , 'GALBANT',
'GALBEES', 'GALBENT', 'GALBERA', 'GALBIEZ', 'GALBONS', 'GALEACE', 'GALEJAI' , 'GALEJAS',
'GALEJAT', 'GALEJER', 'GALEJES', 'GALEJEZ', 'GALENES', 'GALEODE', 'GALERAI' , 'GALERAS',
'GALERAT', 'GALERER', 'GALERES', 'GALEREZ', 'GALERIE', 'GALERNE', 'GALETAI' , 'GALETAS',
'GALETAT', 'GALETEE', 'GALETER', 'GALETES', 'GALETEZ', 'GALETTE', 'GALEUSE' , 'GALGALS',
'GALIBIE', 'GALIBIS', 'GALIBOT', 'GALIDIA', 'GALIDIE', 'GALIONS', 'GALIOTE' , 'GALIPOT',
'GALLECS', 'GALLEUX', 'GALLIUM', 'GALLOIS', 'GALLONS', 'GALLOTS', 'GALLUPS' , 'GALOCHE',
'GALONNA', 'GALONNE', 'GALOPAI', 'GALOPAS', 'GALOPAT', 'GALOPEE', 'GALOPER' , 'GALOPES',
'GALOPEZ', 'GALOPIN', 'GALURES', 'GALURIN', 'GALVANO', 'GAMATES', 'GAMBADA' , 'GAMBADE',
'GAMBIEN', 'GAMBITS', 'GAMELAN', 'GAMELLA', 'GAMELLE', 'GAMETES', 'GAMINAI' , 'GAMINAS',
'GAMINAT', 'GAMINER', 'GAMINES', 'GAMINEZ', 'GAMMARE', 'GAMMEES', 'GAMMONS' , 'GANACHE',
'GANDINS', 'GANGUEE', 'GANGUES', 'GANOIDE', 'GANSAIS', 'GANSAIT', 'GANSANT' , 'GANSEES',
'GANSENT', 'GANSERA', 'GANSIEZ', 'GANSONS', 'GANTAIS', 'GANTAIT', 'GANTANT' , 'GANTEES',
'GANTENT', 'GANTERA', 'GANTIER', 'GANTIEZ', 'GANTOIS', 'GANTONS', 'GAPERON' , 'GAPETTE',
'GARAGES', 'GARAMES', 'GARANCA', 'GARANCE', 'GARANTE', 'GARANTI', 'GARANTS' , 'GARASSE',
'GARATES', 'GARBURE', 'GARCONS', 'GARDAIS', 'GARDAIT', 'GARDANT', 'GARDEES' , 'GARDENT',
'GARDERA', 'GARDEUR', 'GARDIAN', 'GARDIEN', 'GARDIEZ', 'GARDOIS', 'GARDONS' , 'GARENNE',
'GARERAI', 'GARERAS', 'GAREREZ', 'GARGOTA', 'GARGOTE', 'GARIONS', 'GARNIES' , 'GARNIRA',
'GARROTS', 'GASCONS', 'GASOILS', 'GASPARD', 'GASTROS', 'GATAMES', 'GATASSE' , 'GATATES',
'GATEAUX', 'GATERAI', 'GATERAS', 'GATEREZ', 'GATERIE', 'GATEURS', 'GATEUSE' , 'GATIFIA',
'GATIFIE', 'GATINES', 'GATIONS', 'GATISME', 'GATTAIS', 'GATTAIT', 'GATTANT' , 'GATTEES',
'GATTENT', 'GATTERA', 'GATTIEZ', 'GATTONS', 'GAUCHER', 'GAUCHES', 'GAUCHIE' , 'GAUCHIR',
'GAUCHIS', 'GAUCHIT', 'GAUCHOS', 'GAUDIES', 'GAUDIRA', 'GAUFRAI', 'GAUFRAS' , 'GAUFRAT',
'GAUFREE', 'GAUFRER', 'GAUFRES', 'GAUFREZ', 'GAULAGE', 'GAULAIS', 'GAULAIT' , 'GAULANT',
'GAULEES', 'GAULENT', 'GAULERA', 'GAULIEZ', 'GAULOIS', 'GAULONS', 'GAUMAIS' , 'GAUSSAI',
'GAUSSAS', 'GAUSSAT', 'GAUSSEE', 'GAUSSER', 'GAUSSES', 'GAUSSEZ', 'GAVAGES' , 'GAVAMES',
'GAVASSE', 'GAVATES', 'GAVERAI', 'GAVERAS', 'GAVEREZ', 'GAVEURS', 'GAVEUSE' , 'GAVIALS',
'GAVIONS', 'GAVOTES', 'GAVOTTE', 'GAZAGES', 'GAZAMES', 'GAZANIA', 'GAZAOUI' , 'GAZASSE',
'GAZATES', 'GAZELLE', 'GAZERAI', 'GAZERAS', 'GAZEREZ', 'GAZETTE', 'GAZEUSE' , 'GAZIERE',
'GAZIERS', 'GAZIONS', 'GAZODUC', 'GAZOLES', 'GAZONNA', 'GAZONNE', 'GEANTES' , 'GEASTER',
'GEGENES', 'GEHENNE', 'GEIGNES', 'GEIGNEZ', 'GEIGNIS', 'GEIGNIT', 'GEINDRA' , 'GEINDRE',
'GEISHAS', 'GELAMES', 'GELASSE', 'GELATES', 'GELERAI', 'GELERAS', 'GELEREZ' , 'GELIFIA',
'GELIFIE', 'GELINES', 'GELIONS', 'GELISOL', 'GELIVES', 'GELOSES', 'GELULES' , 'GELURES',
'GEMEAUX', 'GEMELLE', 'GEMIMES', 'GEMINAI', 'GEMINAS', 'GEMINAT', 'GEMINEE' , 'GEMINER',
'GEMINES', 'GEMINEZ', 'GEMIRAI', 'GEMIRAS', 'GEMIREZ', 'GEMISSE', 'GEMITES' , 'GEMMAGE',
'GEMMAIL', 'GEMMAIS', 'GEMMAIT', 'GEMMANT', 'GEMMAUX', 'GEMMEES', 'GEMMENT' , 'GEMMERA',
'GEMMEUR', 'GEMMIEZ', 'GEMMONS', 'GEMMULE', 'GENALES', 'GENAMES', 'GENANTE' , 'GENANTS',
'GENASSE', 'GENATES', 'GENCIVE', 'GENDRES', 'GENEPIS', 'GENERAI', 'GENERAL' , 'GENERAS',
'GENERAT', 'GENEREE', 'GENERER', 'GENERES', 'GENEREZ', 'GENESES', 'GENETTE' , 'GENEURS',
'GENEUSE', 'GENIALE', 'GENIAUX', 'GENIENS', 'GENIONS', 'GENIQUE', 'GENISSE' , 'GENITAL',
'GENITIF', 'GENOISE', 'GENOMES', 'GENTILE', 'GENTILS', 'GENTRYS', 'GEOIDES' , 'GEOLIER',
'GERABLE', 'GERAMES', 'GERANCE', 'GERANTE', 'GERANTS', 'GERASSE', 'GERATES' , 'GERBAGE',
'GERBAIS', 'GERBAIT', 'GERBANT', 'GERBEES', 'GERBENT', 'GERBERA', 'GERBEUR' , 'GERBIER',
'GERCAIS', 'GERCAIT', 'GERCANT', 'GERCEES', 'GERCENT' , 'GERCERA',
'INFIRMA', 'INFIRME', 'INFIXES', 'INFLIGE', 'INFLUAI', 'INFLUAS', 'INFLUAT');
	return $liste[array_rand($liste)];
}

function captcha()
{
	$mot = motListe();
	$_SESSION['captcha'] = $mot;
	return $mot;
}
?>

	</div>
</body>
</html>